### ISSUE TITLE
[BUG] MacOs Support

### ISSUE THREAD

**Issue by vessenes** [wsw70/note#1]
**Describe the bug**
When I run note.py on Mac, I get:

```bash
Traceback (most recent call last):
  File "/Users/test/src/note/note.py", line 377, in <module>
    raise NotImplemented
TypeError: exceptions must derive from BaseException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/test/src/note/note.py", line 380, in <module>
    except NotImplemented:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Expected behavior**
On inspection of the code, you should just see if this is running on MacOS, and use the linux settings - we have vi and bash on MacOS.

As it is, I just hardcoded in the linux options, and note.py now works fine.

**Comment by vessenes** [comment]
Also, I don't think you've tested your NotImplemented code path well from that error

**Comment by wsw70** [comment]
Thanks for the feedback!

I added support for MacOS.
I also fixed the Exception with a proper class.

Could you please pull the latest version and see if this works on MacOS (I do nto have access to a Mac)

**Comment by wsw70** [comment]
Closing for now - please re-open if there is still an issue, thanks!
